name: Check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.19.0'
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run check
      - run: npm run check:history
      - uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: 'false'
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: 'false'
          GITLEAKS_ENABLE_SUMMARY: 'false'
